# Programming for Data Analysis - ASSIGNMENT


## Python numpy.random package

### 1. Overall purpose of the package

NumPy (Numerical Python) is a Python library that is specialsied and optimised to work very fast and efficient with multidimensional array objects. It is a fundamental library for scientific computing in Python providing high-performance multidimensional array object, and tools for working with them. It relies on packages implemented in another language (e.g. C) to perform efficient and fast computations.

**numpy.random** package is used for generating random (actually pseudorandom) data based on a certain distribution.

### 2. “Simple random data” and “Permutations” functions

#### Simple random data

A set of several functions that return a various types of random numbers, depending of the parameters passed.
<br>Few examples:

- **rand(_d0, d1, …, dn_)**	Returns random values in a given shape. It creatse an array of the given shape and populates it with random samples from a uniform distribution over the interval [0, 1).

In [6]:
import numpy as np
np.random.rand(2,3,4)

array([[[0.53154628, 0.18501098, 0.39878979, 0.65786153],
        [0.05148239, 0.3797957 , 0.43649786, 0.66410911],
        [0.29372863, 0.47389332, 0.43754765, 0.12921784]],

       [[0.74876081, 0.52055811, 0.72829773, 0.59806915],
        [0.52409015, 0.40904998, 0.22053303, 0.42823242],
        [0.1656973 , 0.22477137, 0.92697813, 0.22335434]]])

- **randn(_d0, d1, …, dn_)**	Returns a sample(s) from the “standard normal” distribution.

In [7]:
np.random.randn(2, 2)

array([[ 0.06965529, -1.77719763],
       [-0.08764564,  0.28842431]])

- **random\_sample([_size_])**	Returns random floats in the half-open interval [0.0, 1.0)

In [8]:
np.random.random_sample((3, 2, 4))

array([[[0.29105162, 0.42524967, 0.46514163, 0.1456869 ],
        [0.81083346, 0.71796305, 0.86740461, 0.09158114]],

       [[0.64367545, 0.0631807 , 0.79439918, 0.37749852],
        [0.61897001, 0.73609359, 0.23150347, 0.70019214]],

       [[0.11148499, 0.22464805, 0.51943895, 0.91303778],
        [0.37620545, 0.36097736, 0.4421671 , 0.30068578]]])

#### Permutations

Contains two functions that "randomise" given dataset:

- **shuffle(_arr_)**	Modifies a sequence in-place by shuffling its contents.

### 3. Numpy "Distributions" functions

- **geometric(p[, size])** Draws samples from the geometric distribution.

- **logseries(p[, size])**	Draws samples from a logarithmic series distribution.

- **normal([loc, scale, size])** Draws random samples from a normal (Gaussian) distribution.

- **poisson([lam, size])**	Draw samples from a Poisson distribution.

- **rayleigh([scale, size])**	Draws samples from a Rayleigh distribution.

### 4. "Seeds" in generating pseudorandom numbers

A random seed is a number (or vector) used to initialize a pseudorandom number generator.
<br>
For a seed to be used in a pseudorandom number generator, it does not need to be random. Because of the nature of number generating algorithms, so long as the original seed is ignored, the rest of the values that the algorithm generates will follow probability distribution in a pseudorandom manner.

## References

[1] https://docs.scipy.org/doc/numpy/
<br>
[2] http://www.numpy.org/
<br>
[3] https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html#
<br>
[4] https://en.wikipedia.org/wiki/NumPy